# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Create settings.xml
      run: |
        mkdir -p ~/.m2
        echo '<settings>' > ~/.m2/settings.xml
        echo '  <servers>' >> ~/.m2/settings.xml
        echo '    <server>' >> ~/.m2/settings.xml
        echo '      <id>github</id>' >> ~/.m2/settings.xml
        echo '      <username>${{ github.actor }}</username>' >> ~/.m2/settings.xml
        echo '      <password>${{ secrets.GITHUB_TOKEN }}</password>' >> ~/.m2/settings.xml
        echo '    </server>' >> ~/.m2/settings.xml
        echo '  </servers>' >> ~/.m2/settings.xml
        echo '</settings>' >> ~/.m2/settings.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s ~/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

